// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://crngbsalevfexrumrsao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNybmdic2FsZXZmZXhydW1yc2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzA2NjQsImV4cCI6MjA3MDYwNjY2NH0.LOz4iEMurYPqcRq_hkRjKWDB9dQhyMOEWDM8ml_W8sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);